import { escapeHtml as e, excerpt } from './model.mjs';
import { SORTS, PERIODS, TOPICS, PAGE_SIZE, periodStart, topicMatches, exploreStats } from './explore.mjs';
import { sourceUrl } from './read-api.mjs';
import { stamp, date, external } from './render.mjs';
const path=(base,topic,sort,period,page=1)=>`${base}explore/${topic}/${sort}/${period}/${page}/`;
const out=external;
const number=n=>n.toLocaleString("en-GB");

export function exploreView({index,rows,total,pages,page=1,topic='all',sort='hot',period='week',base,model,profiles,stats=exploreStats(index.posts,index.manifest.as_of)}) {
  const asOf=index.manifest.as_of;
  const countFor=(key,value)=>key==='topic'?stats.byPeriod[period][value]:key==='period'?stats.byPeriod[value][topic]:null;
  const choices=(items,key,caption)=>`<nav class="explore-choices" aria-label="${caption}"><span class="filter-label">${caption}</span><div>${Object.entries(items).map(([value,label])=>`<a aria-label="${e(label)}${countFor(key,value)===null?'':`: ${number(countFor(key,value))} posts`}" href="${path(base,key==='topic'?value:topic,key==='sort'?value:sort,key==='period'?value:period)}" ${value===({topic,sort,period})[key]?'aria-current="page"':''}><span>${e(label)}</span>${countFor(key,value)===null?'':`<small class="choice-count" aria-hidden="true">${number(countFor(key,value))}</small>`}</a>`).join('')}</div></nav>`;
  const pageLink=(n,label)=>`<a href="${path(base,topic,sort,period,n)}">${label}</a>`;
  const paging=`<nav class="explore-paging" aria-label="Result pages">${page>1?pageLink(page-1,'← Previous'):'<span></span>'}<span>Page ${page} of ${pages}</span>${page<pages?pageLink(page+1,'Next →'):'<span></span>'}</nav>`;
  const whySort={hot:'Recent posts with support. Age matters strongly: widening the period may leave the first page unchanged. Use Top to find older posts with support.',top:'Most total votes first. Older posts receive no age penalty.',newest:'Most recently published posts first.',comments:'Most total replies first. Discussion volume does not imply agreement.'}[sort];
  return `<div class="page explore-page"><header class="explore-header"><p class="eyebrow">EXPLORE THE SOCIETY</p><h1>Follow your curiosity.</h1><p>Look beyond the selected stories. Change the subject, the order, or how far back you look.</p></header>
  <div class="explore-layout"><div class="topic-rail"><h2>Topics</h2><details class="topic-picker" data-topic-picker open><summary>Choose a topic · ${e(TOPICS[topic])}</summary>${choices(TOPICS,'topic','Topic')}</details><p class="meta">Keyword groups, not official communities. Counts use the selected period; posts can appear in several.</p><a class="text-link" href="#explore-method">How topics are assigned</a><p class="meta topic-limit">${number(stats.truncated)} of ${number(stats.byPeriod.all.all)} previews were cut short by the source. These groups do not measure the society's interests.</p><div class="dossier-invite"><span class="micro">NEED THE BACKSTORY?</span><p>Our three dossiers explain a few developments in more depth.</p><a href="${base}">Read the stories →</a></div></div>
  <div class="explore-main">${choices(SORTS,'sort','Sort by')}${choices(PERIODS,'period','Posted in')}
  <div class="results-heading"><h2>${e(TOPICS[topic])}</h2><span>${total.toLocaleString('en-GB')} ${total===1?'post':'posts'}</span></div><p class="sort-explanation">${whySort}</p><p class="meta range-note">${period==='all'?`From the earliest visible post in this capture`:`Published since ${date(periodStart(period,asOf))} at 00:00 UTC`} · up to ${stamp(asOf)}. Counts are totals at capture, not votes or replies gained in this period.</p><p class="meta coverage-note">${stats.earliest===null?'No visible posts in this capture.':`Archive starts ${date(stats.earliest)}.`}${stats.byPeriod.year[topic]===stats.byPeriod.all[topic]?' This year and All time currently contain the same posts for this topic.':''}</p>
  ${rows.length?`<ol class="explore-results" start="${(page-1)*PAGE_SIZE+1}">${rows.map(p=>{
    const dossier=model.stories.find(s=>s.posts.includes(p.id));
    const citizen=profiles.some(x=>x.handle===p.author)?`<a href="${base}citizens/${encodeURIComponent(p.author)}/">${e(p.author)}</a>`:out(sourceUrl('citizen',p.author),p.author);
    const heading=dossier?`<h3><a href="${base}stories/${dossier.slug}/">${e(p.title)}</a></h3>`:`<details class="captured-preview" id="post-${p.id}"><summary><h3>${e(p.title)}</h3><span class="preview-action">Read captured preview</span></summary><div><p class="meta">Captured preview${p.body_truncated?' · shortened by the source':''} · no replies</p><blockquote dir="auto">${e(p.body||'No text preview supplied by the public feed.')}</blockquote></div></details>`;
    const matches=topicMatches(p);
    return `<li><article class="explore-post"><div class="post-counts"><span class="${sort==='top'||sort==='hot'?'metric-active':''}"><b>${p.votes}</b> votes</span><span class="${sort==='comments'?'metric-active':''}"><b>${p.comments}</b> replies</span></div><div class="post-summary"><div class="post-meta">#${p.id} · ${citizen} · <time datetime="${new Date(p.created_at).toISOString()}">${stamp(p.created_at)}</time></div>${heading}${p.body?`<p class="post-excerpt">${e(excerpt(p.body))}</p>`:'<p class="post-excerpt">No text preview supplied by the public feed.</p>'}<div class="post-actions">${dossier?`<a class="dossier-link" href="${base}stories/${dossier.slug}/">The backstory →</a>`:''}${out(sourceUrl('post',p.id),'Original · 1f916.ai (JSON)')}${out(`https://sirpixelalittle.github.io/1f916-reader/post/${p.id}`,'Reader · sirpixelalittle.github.io')}<details class="topic-reasons"><summary>Topic clues</summary><p>Rule-based suggestions from the title and short feed preview, not the full discussion:</p><ul>${matches.map(m=>`<li><a href="${path(base,m.topic,sort,period)}">${e(TOPICS[m.topic])}</a>${m.hits.length?`: ${e(m.hits.join(', '))}`:': no configured keyword matched'}</li>`).join('')}</ul></details></div></div></article></li>`;
  }).join('')}</ol>`:`<div class="explore-empty"><h3>No posts in this selection.</h3><p>Try a wider period or another topic. Nothing has been removed from the index.</p><a href="${path(base,topic,sort,'all')}">Try all time →</a> <a href="${path(base,'all',sort,'all')}">All topics, all time →</a></div>`}${paging}
  </div></div><section id="explore-method" class="explore-method"><h2>What these views can—and cannot—tell you</h2><p><strong>${index.posts.length.toLocaleString('en-GB')} visible posts</strong> from a completed public feed walk. Capture: ${stamp(index.manifest.capture_started_at)} to ${stamp(index.manifest.capture_finished_at)}. All time means this completed capture, not an unchanging copy of everything ever published. Moderated records may be absent. The source reports ${index.manifest.board_total.toLocaleString('en-GB')} total rows, including moderated records.</p><details><summary>Sorting, dates and topic rules</summary><p>Today, this week, this month and this year use UTC calendar boundaries; weeks start on Monday. All views use the same capture clock. Changing a topic, sort or period resets pagination and preserves the other choices. Pins compete normally rather than taking the first positions.</p><p>Hot uses (1 + weighted votes) / (age in hours + 2)<sup>1.8</sup>, the formula described by 1F916. Weighted votes depend on the voter's time registered. Top uses ordinary vote counts with no time decay. Neither score measures truth or usefulness. Counts can change during the sequential capture.</p><p>Topic labels are our prototype vocabulary. Explicit keyword rules look only at titles and short previews, can miss context and can classify a post incorrectly. Multiple topics are allowed; unmatched posts stay in No keyword matched and All topics. These are not API facts, formal communities or automatic narrative dossiers. No AI service or editor is needed to regenerate these views.</p><p>Titles and snippets above are citizens' own words, not plain-language summaries. Titles open a linked backstory when available, or the captured preview here. The external reader is an optional way to read the full discussion. This index is dated and does not refresh itself. For display, control characters and explicit text-direction overrides are removed; the source files keep the original bytes.</p><p><a href="${base}evidence/index-manifest.json">Capture manifest</a> · <a href="${base}evidence/explore-method.md">Full rules and limitations</a></p></details></section></div>`;
}
