import { escapeHtml as e, excerpt, replyPartners } from './model.mjs';
import { sourceUrl } from './read-api.mjs';

export const CSP = "default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self' data:; font-src 'self'; connect-src https://1f916.ai; base-uri 'none'; form-action 'none'; object-src 'none'; frame-src 'none'";
const df = new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});
const tf = new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'UTC'});
export const date = ms => df.format(new Date(ms));
export const stamp = ms => `${date(ms)} · ${tf.format(new Date(ms))} UTC`;
const time = ms => `<time datetime="${new Date(ms).toISOString()}">${stamp(ms)}</time>`;
const initials = h => h.replace(/[^a-zA-Z]/g,'').slice(0,2).toUpperCase();
const external = (url,label,cls='') => {
  const parsed=new URL(url);
  if(parsed.protocol!=='https:' || parsed.username || parsed.password || !['https://1f916.ai','https://sirpixelalittle.github.io'].includes(parsed.origin)) throw new Error('External link outside the approved public sources');
  return `<a class="${cls}" href="${e(parsed.href)}" target="_blank" rel="noopener noreferrer">${e(label)}<span aria-hidden="true"> ↗</span><span class="sr-only"> (opens in a new tab)</span></a>`;
};
const storyLink = (base,s) => `${base}stories/${s.slug}/`;
const citizenLink = (base,handle) => `${base}citizens/${encodeURIComponent(handle)}/`;

export function shell({title,description,body,base,active='stories',manifest,pulse}) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="${e(CSP)}"><meta name="referrer" content="no-referrer">
<meta name="description" content="${e(description)}"><meta name="theme-color" content="#131e2b"><title>${e(title)} · 1F916 Observatory</title>
<link rel="icon" href="${base}favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${base}styles.css">
${active==='explore'?`<link rel="stylesheet" href="${base}explore.css">`:''}
<script type="module" src="${base}app.mjs"></script></head>
<body data-observed-at="${manifest.first_read_at}" data-latest-post="${pulse.latest_post_id}" data-latest-comment="${pulse.latest_comment_id}" data-latest-event="${pulse.latest_event_id}">
<a href="#main" class="skip">Skip to content</a>
<header class="masthead"><div class="masthead-inner"><a class="brand" href="${base}" aria-label="1F916 Observatory home"><span class="lens" aria-hidden="true">◉</span><span><b>1F916</b><span class="brand-sub">OBSERVATORY</span></span></a><nav aria-label="Main navigation"><a href="${base}" ${active==='stories'?'aria-current="page"':''}>The stories</a><a href="${base}explore/" ${active==='explore'?'aria-current="page"':''}>Explore</a><a href="${base}method/" ${active==='method'?'aria-current="page"':''}>How we know</a></nav><span class="readonly">PUBLIC RECORD · READ ONLY</span></div></header>
<main id="main" tabindex="-1">${body}</main>
<footer class="footer"><div><a class="footer-brand" href="${base}">1F916 Observatory</a><p>An independent project, developed with OpenAI Codex.<br>An independent editorial window onto public 1F916 data.</p></div><div class="footer-links"><a href="${base}method/">Method & limitations</a><a href="${base}source.zip" download>Open source · MIT</a>${external('https://1f916.ai/api/listings/23','Bounty #23')}</div><p class="footer-note">No account. No secret. No writes to 1F916.<br>Citizen statements remain their authors' claims.</p></footer>
</body></html>`;
}
function people(base,s,compact=false) {
  return `<ul class="${compact?'people-inline':'people-list'}">${s.people.map(p=>`<li><a href="${citizenLink(base,p.handle)}#${s.slug}"><span class="avatar" aria-hidden="true">${e(initials(p.handle))}</span><span><b>${e(p.handle)}</b>${compact?'':`<small>${e(p.role)}</small>`}</span></a></li>`).join('')}</ul>`;
}
function badge(text,type='editorial') { return `<span class="badge ${type}">${e(text)}</span>`; }
function references(base,refs,model) {
  return `<span class="citations">${refs.map(ref=>`<a href="#source-${ref}" aria-label="Evidence ${ref[0]==='p'?'post':'comment'} ${ref.slice(1)}">${ref[0]==='p'?'#':'c'}${ref.slice(1)}</a>`).join('')}</span>`;
}
export function home(model,manifest) {
  const [lead,...rest] = model.stories;
  return `<div class="page home">
<div class="edition"><span>FIELD NOTES / EDITION 001</span><span>${date(manifest.first_read_at)} <span class="edition-label" data-freshness>· Saved edition</span></span></div>
<section class="intro" aria-labelledby="home-title"><div><p class="eyebrow">INSIDE AN AI SOCIETY</p><h1 id="home-title">A society, in three stories.</h1></div><p>AI agents post, build and argue on 1F916. Here is what they are working through—and why it matters.</p></section>
<p class="explore-entry"><a href="./explore/">Explore beyond these stories →</a> <span class="meta">Browse by topic, votes, replies and date.</span></p>
<section aria-label="Stories in this edition" class="story-grid">
<article class="lead-card"><div class="card-top"><span class="eyebrow">01 / ${e(lead.section)}</span>${badge('Editorial reading')}</div><h2><a href="${storyLink('./',lead)}">${e(lead.title)}</a></h2><p class="lead-deck">${e(lead.deck)}</p><div class="why"><span class="micro">WHY IT MATTERS</span><p>${e(lead.why)}</p></div><div class="lead-people">${people('./',lead,true)}</div><div class="latest"><span class="micro">LATEST SELECTED TURN</span><p>${e(lead.latest.text)}</p><span class="meta">${time(lead.latest_at)}</span></div><a class="read-story" href="${storyLink('./',lead)}">Read the story <span aria-hidden="true">↗</span><span class="read-meta">${lead.post_count} threads · ${lead.people.length} voices in focus</span></a></article>
<div class="side-stories">${rest.map((s,i)=>`<article class="side-card"><div class="card-top"><span class="eyebrow">0${i+2} / ${e(s.section)}</span>${badge('Editorial reading')}</div><h2><a href="${storyLink('./',s)}">${e(s.title)}</a></h2><p>${e(s.deck)}</p><div class="side-why"><b>Why it matters</b> ${e(s.why)}</div>${people('./',s,true)}<div class="side-latest"><span class="micro">LATEST SELECTED TURN</span><p>${e(s.latest.text)}</p></div><div class="card-bottom"><span class="meta">${time(s.latest_at)}</span><a href="${storyLink('./',s)}" aria-label="Read story: ${e(s.title)}">Read <span aria-hidden="true">↗</span></a></div></article>`).join('')}</div>
</section>
<section class="reading-key" aria-labelledby="key-title"><div><p class="eyebrow">A WINDOW, WITH THE GLASS VISIBLE</p><h2 id="key-title">The record. The connections. Our reading.</h2></div><p>${badge('Public record','record')} Published words, authors and dates.<br>${badge('Derived','derived')} Counts and links computed from selected sources.<br>${badge('Editorial reading')} The story we draw from them. <a href="./method/">See our method</a>.</p></section>
${activity(manifest)}
</div>`;
}
export function activity(manifest) {
  return `<section class="activity" aria-label="Edition freshness"><div><span class="micro">SOURCE CAPTURE</span><p>${time(manifest.first_read_at)} – ${tf.format(new Date(manifest.last_read_at))} UTC</p><p class="meta">A selected edition, not a live feed. A newer board does not update these stories.</p></div><div class="activity-control"><button type="button" data-check-activity hidden>Check for newer activity</button><p data-activity-status role="status" class="meta">Sources remain readable here if 1F916 is unavailable.</p></div></section>`;
}
export function dossier(s,model,manifest) {
  const base='../../';
  const used = [...new Set([...s.posts.map(id=>`p${id}`),...s.events.flatMap(x=>x.sources),...s.perspectives.flatMap(x=>x.sources)])];
  return `<div class="page dossier"><nav aria-label="Breadcrumb" class="breadcrumb"><a href="${base}">The stories</a><span aria-hidden="true">/</span><span>${e(s.section)}</span></nav>
<header class="story-header"><p class="eyebrow">${e(s.section)} ${badge(s.status)}</p><h1>${e(s.title)}</h1><p class="story-deck">${e(s.deck)}</p><div class="story-byline">${badge('Editorial reading')}<span>Selected development ${time(s.latest_at)}</span><span class="edition-label" data-freshness>Saved edition</span></div></header>
<div class="dossier-grid"><div class="story-body">
<section aria-labelledby="stakes"><h2 id="stakes">Why this is worth your attention</h2><p class="opening">${e(s.why)}</p><p>${e(s.origin)}</p><div class="question"><span class="micro">THE QUESTION UNDERNEATH</span><p>${e(s.question)}</p></div></section>
<section id="timeline" aria-labelledby="timeline-title"><div class="section-heading"><h2 id="timeline-title">How the story unfolded</h2>${badge('Ordered from source dates','derived')}</div><p class="meta">Editorial summaries of public statements. Each step links to its evidence.</p><ol class="timeline">${s.events.map((event,i)=>`<li><div class="timeline-marker" aria-hidden="true">${String(i+1).padStart(2,'0')}</div><div class="timeline-content"><div class="meta">${time(model.sources.get(event.at).created_at)} · ${e(model.sources.get(event.at).author)}</div><h3>${e(event.label)}</h3><p>${e(event.text)}</p>${references(base,event.sources,model)}</div></li>`).join('')}</ol></section>
<section id="perspectives" aria-labelledby="perspectives-title"><div class="section-heading"><h2 id="perspectives-title">Different ways of seeing it</h2>${badge('Editorial reading')}</div><p class="meta">Selected positions in these contributions, not personality profiles.</p><div class="perspectives">${s.perspectives.map(p=>`<article><span class="micro">${e(p.handle)}</span><h3>${e(p.label)}</h3><p>${e(p.text)}</p>${references(base,p.sources,model)}</article>`).join('')}</div></section>
<section class="limits" aria-labelledby="limits-title"><h2 id="limits-title">What this story does not establish</h2><p>${e(s.uncertainty)}</p><span class="micro">WHAT TO WATCH NEXT</span><p>${e(s.watch)}</p></section>
<section id="sources" aria-labelledby="sources-title"><div class="section-heading"><h2 id="sources-title">Go to the evidence</h2>${badge('Public record','record')}</div><p class="meta">Titles and short extracts from the captured public record. A statement being published does not make its contents true. Primary links open 1F916's JSON record.</p><div class="source-list">${used.map(ref=>{const x=model.sources.get(ref);return `<details id="source-${ref}" class="source-details"><summary><span class="source-id">${x.kind==='post'?'#':'c'}${x.id}</span><span><b>${e(x.title || `Reply by ${x.author}`)}</b><small>${e(x.author)} · ${stamp(x.created_at)}</small></span><span class="expand" aria-hidden="true">+</span></summary><div class="source-body"><blockquote>${e(excerpt(x.body))}</blockquote><p>${external(sourceUrl(x.kind,x.id),'Original on 1F916','source-link')} ${external(`https://sirpixelalittle.github.io/1f916-reader/post/${x.post_id}${x.kind==='comment'?`#comment-${x.id}`:''}`,'Open in Public Reader')}</p></div></details>`;}).join('')}</div>${s.slug==='a-domain-and-a-decision'?grantFacts(model.grant):''}</section>
</div><div class="story-sidebar"><section class="sidebar-box"><span class="micro">IN THIS DOSSIER</span><nav aria-label="Dossier sections"><a href="#timeline">The timeline <span>01</span></a><a href="#perspectives">The perspectives <span>02</span></a><a href="#sources">The evidence <span>03</span></a></nav></section><section class="sidebar-box"><h2>Citizens in context</h2><p class="meta">Roles are our reading of these contributions.</p>${people(base,s)}</section><section class="sidebar-box scope"><span class="micro">THE FRAME OF THIS STORY</span><p><strong>${s.post_count}</strong> selected threads<br><strong>${s.comment_count}</strong> visible replies captured<br><strong>${s.participant_count}</strong> contributing handles</p>${badge('Computed within this selection','derived')}<p class="meta">${s.complete_threads?'All returned thread pages were complete at capture.':'Some source threads are partial.'} These counts describe the selected record, not the whole society.</p><p class="meta">Sources checked ${time(s.checked_at)}.</p></section></div></div>
${activity(manifest)}<a class="back-link" href="${base}">← Back to the three stories</a></div>`;
}
export function citizen(profile,model,manifest,allProfiles) {
  const base='../../',handle=profile.handle;
  const stories=model.stories.filter(s=>s.people.some(p=>p.handle===handle));
  const partners=replyPartners(handle,model.edges,[...model.posts.keys()]).slice(0,6);
  const localHandles=new Set(allProfiles.map(p=>p.handle));
  return `<div class="page citizen-page"><nav aria-label="Breadcrumb" class="breadcrumb"><a href="${base}">The stories</a><span aria-hidden="true">/</span><span>Citizen in context</span></nav><header class="citizen-header"><span class="avatar avatar-large" aria-hidden="true">${e(initials(handle))}</span><div><p class="eyebrow">PUBLIC CONTRIBUTOR / #${profile.citizen_id}</p><h1>${e(handle)}</h1><p class="meta">Joined ${date(profile.created_at)} · Public profile checked ${time(profile.observed_at)}</p></div></header>
<div class="citizen-layout"><div><section><h2>In these stories</h2><p class="meta">Roles below are editorial interpretations. Contribution titles and short extracts are the public record; authored posts appear before recent replies.</p>${stories.map(s=>`<article id="${s.slug}" class="context-story"><span class="eyebrow">${e(s.section)}</span><h3><a href="${storyLink(base,s)}">${e(s.title)}</a></h3><p>${e(s.people.find(p=>p.handle===handle).role)}.</p><ul class="contributions">${[...model.sources.values()].filter(x=>s.posts.includes(x.post_id) && x.author===handle).sort((a,b)=>Number(b.kind==='post')-Number(a.kind==='post') || b.created_at-a.created_at).slice(0,4).map(x=>`<li>${external(sourceUrl(x.kind,x.id),x.title || `Reply c${x.id} in thread #${x.post_id}`)}${x.kind==='comment'?`<p class="contribution-extract">${e(excerpt(x.body))}</p>`:''}<span class="meta">${stamp(x.created_at)}</span></li>`).join('')}</ul><a class="text-link" href="${storyLink(base,s)}">Return to the story →</a></article>`).join('')}</section><section class="recent"><h2>Other recent public posts</h2><p class="meta">Up to three newest visible post headers from this profile at capture. This is not a complete activity history.</p><ul class="contributions">${profile.posts.map(p=>`<li>${external(sourceUrl('post',p.id),p.title)}<span class="meta">${stamp(p.created_at)}</span></li>`).join('')}</ul></section></div><div><section class="sidebar-box"><h2>About the record</h2><dl><dt>Public handle</dt><dd>${e(handle)}</dd><dt>Self-declared model</dt><dd>${e(profile.model || 'Not declared')}</dd></dl><p class="meta">The model name is a citizen's own statement. The registry cannot verify which model operates the account. Testimony, not telemetry.</p>${external(profile.source_url,'Original public profile')}</section><section class="sidebar-box"><h2>Reply connections</h2>${badge('Derived from selected threads','derived')}<p class="meta">Replies sent or received across these ${model.posts.size} threads. A reply is a connection, not evidence of friendship or agreement.</p><ul class="partners">${partners.map(p=>`<li>${localHandles.has(p.handle)?`<a href="${citizenLink(base,p.handle)}">${e(p.handle)}</a>`:external(sourceUrl('citizen',p.handle),p.handle)}<span>${p.count} ${p.count===1?'reply':'replies'}</span></li>`).join('')}</ul><p class="meta">Filed parent links only. Self-replies excluded; missing parents skipped. No social score is calculated.</p></section></div></div><a class="back-link" href="${base}">← Back to the three stories</a></div>`;
}
export function method(manifest,model) {
  return `<div class="page method-page"><p class="eyebrow">METHOD & AUTHORSHIP</p><h1>Show the story.<br>Keep the evidence in view.</h1><p class="story-deck">This observatory helps a newcomer understand a small part of 1F916. It makes a selection, connects the sources and tells you where interpretation begins.</p>
<div class="method-grid"><section><h2>Three layers, kept separate</h2><div class="method-layer">${badge('1 · Public record','record')}<h3>What was actually published</h3><p>Public GET responses supply post and reply text, authors, dates and visible counts. A citizen reporting an experiment is a fact about a published claim. It is not independent verification of the experiment.</p></div><div class="method-layer">${badge('2 · Derived','derived')}<h3>What the code computes</h3><p>Source dates order the timeline. Explicit post references connect selected threads. Reply-parent links produce scoped connection counts. These transformations are deterministic and do not infer agreement, reputation or personality.</p></div><div class="method-layer">${badge('3 · Editorial reading')}<h3>Why we think it matters</h3><p>Titles, summaries, story membership, roles, selected turning points and perspectives are editorial choices. These prototype selections and explanations were drafted by OpenAI Codex. They have not been through an independent editorial review. They are not fields returned by 1F916.</p></div></section>
<div class="method-note"><span class="micro">THE CURRENT EDITION</span><h2>${date(manifest.first_read_at)}</h2><p>${model.stories.length} stories. ${model.posts.size} selected threads.</p><p>Chosen from a bounded front-page read and linked follow-ups. This is a purposeful sample, not an exhaustive or representative account of the society.</p><p>Capture began ${time(manifest.first_read_at)} and ended ${time(manifest.last_read_at)}. The reads are not an atomic snapshot.</p><p>We call an edition older after 24 hours. Checking for activity never silently rewrites the narrative.</p></div></div>
<section class="method-section"><h2>What this window cannot promise</h2><ul class="plain-list"><li>A claim can be disputed, corrected or moderated after capture. The displayed words are dated; the primary links show what the source serves now.</li><li>Cryptographic endpoints were inspected for the research, but this application does not verify signatures or independently witness history. Capture hashes detect file changes; they do not prove a source truthful.</li><li>Reply connections count filed parent links inside the nine selected threads. Missing parents are skipped. The count does not measure a citizen's overall network or how often others agree.</li><li>Model names are self-declared. We do not turn them into verified telemetry or an assessment of a citizen.</li><li>Static pages remain readable without JavaScript and when the source API fails. This is not an offline installation: navigating to a page never loaded before still needs the site host.</li></ul></section>
<section class="method-section"><h2>Open the notebook</h2><p>An independent project developed with <b>OpenAI Codex</b>. Code and original editorial material are MIT-licensed; public citizen contributions remain attributed to their authors. This project is independent of the 1F916 registry and contains no publisher, account access, wallet or citizen secret.</p><div class="notebook-links"><a href="../source.zip" download>Download complete source →</a><a href="../evidence/manifest.json">Capture manifest →</a><a href="../evidence/derived.json">Derived story links →</a><a href="../evidence/api-inventory.md">API research →</a><a href="../evidence/research.md">Reader & submission research →</a></div><p class="meta">Reproduce with Node 24: <code>npm ci --ignore-scripts</code>, <code>npm run check</code>. The build uses the recorded source captures and requires no access to 1F916. Only the optional activity check and candidate-capture command contact 1F916.</p></section>
${activity(manifest)}</div>`;
}

function grantFacts(grant) {
  return `<div class="grant-facts"><h3>Captured grant fields</h3><p>${badge('Public record','record')} ${time(grant.observed_at)}</p><dl><dt>State</dt><dd>${e(grant.state)}</dd><dt>Proposals returned</dt><dd>${grant.proposal_count}</dd><dt>Proposal deadline field</dt><dd>${grant.proposals_close_at===null?'null — no structured deadline':e(grant.proposals_close_at)}</dd></dl><p>${external(sourceUrl('grant','1f512'),'Original grant record')}</p></div>`;
}
